import numpy as np

from .utils import get_node_importance

node_names = [
    'A feed (stream 1)',
    'D feed (stream 2)',
    'E feed (stream 3)',
    'A and C feed (stream 4)',
    'Recycle flow (stream 8)',
    'Reactor feed rate (stream 6)',
    'Reactor pressure',
    'Reactor level',
    'Reactor temperature',
    'Purge rate (stream 9)',
    'Product separator temperature',
    'Product separator level',
    'Product separator pressure',
    'Product separator underflow (stream 10)',
    'Stripper level',
    'Stripper pressure',
    'Stripper underflow (stream 11)',
    'Stripper temperature',
    'Stripper steam flow',
    'Compressor work',
    'Reactor cooling water outlet temperature',
    'Stripper temperature',
    'Reactor feed analysis (Component A)',
    'Reactor feed analysis (Component B)',
    'Reactor feed analysis Component C)',
    'Reactor feed analysis (Component D)',
    'Reactor feed analysis (Component E)',
    'Reactor feed analysis (Component F)',
    'Purge gas analysis (Component A)',
    'Purge gas analysis (Component B)',
    'Purge gas analysis (Component C)',
    'Purge gas analysis (Component D)',
    'Purge gas analysis (Component E)',
    'Purge gas analysis (Component F)',
    'Purge gas analysis (Component G)',
    'Purge gas analysis (Component H)',
    'Product analysis (Component D)',
    'Product analysis (Component E)',
    'Product analysis (Component F)',
    'Product analysis (Component G)',
    'Product analysis (Component H)',
    'D feed flow (stream 2)',
    'E feed flow (stream 3)',
    'A feed flow (stream 1)',
    'A and C feed flow (stream 4)',
    'Compressor recycle valve',
    'D feed flow (stream 2)',
    'D feed flow (stream 2)',
    'D feed flow (stream 2)',
    'D feed flow (stream 2)',
    'D feed flow (stream 2)',
    'D feed flow (stream 2)'
 ]

nodes_description = [
    {'node_id' : 1, 'color':0, 'shape':0},
    {'node_id' : 2, 'color':0, 'shape':0},
    {'node_id' : 3, 'color':0, 'shape':0},
    {'node_id' : 4, 'color':0, 'shape':0},
    {'node_id' : 5, 'color':0, 'shape':0},
    {'node_id' : 6, 'color':0, 'shape':0},
    {'node_id' : 7, 'color':1, 'shape':0},
    {'node_id' : 8, 'color':2, 'shape':0},
    {'node_id' : 9, 'color':3, 'shape':0},
    {'node_id' : 10, 'color':0, 'shape':0},
    {'node_id' : 11, 'color':3, 'shape':0},
    {'node_id' : 12, 'color':2, 'shape':0},
    {'node_id' : 13, 'color':1, 'shape':0},
    {'node_id' : 14, 'color':0, 'shape':0},
    {'node_id' : 15, 'color':2, 'shape':0},
    {'node_id' : 16, 'color':1, 'shape':0},
    {'node_id' : 17, 'color':0, 'shape':0},
    {'node_id' : 18, 'color':3, 'shape':0},
    {'node_id' : 19, 'color':0, 'shape':0},
    {'node_id' : 20, 'color':5, 'shape':0},
    {'node_id' : 21, 'color':3, 'shape':0},
    {'node_id' : 22, 'color':3, 'shape':0},
    {'node_id' : 23, 'color':4, 'shape':0},
    {'node_id' : 24, 'color':4, 'shape':0},
    {'node_id' : 25, 'color':4, 'shape':0},
    {'node_id' : 26, 'color':4, 'shape':0},
    {'node_id' : 27, 'color':4, 'shape':0},
    {'node_id' : 28, 'color':4, 'shape':0},
    {'node_id' : 29, 'color':4, 'shape':0},
    {'node_id' : 30, 'color':4, 'shape':0},
    {'node_id' : 31, 'color':4, 'shape':0},
    {'node_id' : 32, 'color':4, 'shape':0},
    {'node_id' : 33, 'color':4, 'shape':0},
    {'node_id' : 34, 'color':4, 'shape':0},
    {'node_id' : 35, 'color':4, 'shape':0},
    {'node_id' : 36, 'color':4, 'shape':0},
    {'node_id' : 37, 'color':4, 'shape':0},
    {'node_id' : 38, 'color':4, 'shape':0},
    {'node_id' : 39, 'color':4, 'shape':0},
    {'node_id' : 40, 'color':4, 'shape':0},
    {'node_id' : 41, 'color':0, 'shape':1},
    {'node_id' : 42, 'color':0, 'shape':1},
    {'node_id' : 43, 'color':0, 'shape':1},
    {'node_id' : 44, 'color':0, 'shape':1},
    {'node_id' : 45, 'color':0, 'shape':1},
    {'node_id' : 46, 'color':0, 'shape':1},
    {'node_id' : 47, 'color':0, 'shape':1},
    {'node_id' : 48, 'color':0, 'shape':1},
    {'node_id' : 49, 'color':0, 'shape':1},
    {'node_id' : 50, 'color':0, 'shape':1},
    {'node_id' : 51, 'color':0, 'shape':1},
    {'node_id' : 52, 'color':0, 'shape':1},
]

COLORS = {0: 'rgb(113, 186, 255)', 
          1: 'rgb(51, 153, 0)', 
          2: 'rgb(255, 213, 0)', 
          3: 'rgb(255, 109, 84)', 
          4: 'rgb(153, 113, 194)', 
          5: 'rgb(192, 192, 192)'}

SHAPES = {0: 'box', 
          1: 'circle'}

def get_node_color_and_shape(node_id):
    return (COLORS[nodes_description[node_id]['color']], SHAPES[nodes_description[node_id]['shape']])


def get_node_info(baseline_metrics, node_importance_matrix, node_id, topk=3):
    result = f'{node_names[node_id]} \n \n Most significant faults:'
    top_importance = np.argpartition(get_node_importance(node_importance_matrix, node_id), -topk)[-topk:].tolist()
    for _, i in enumerate(top_importance):
        result += f'\n {i}. {baseline_metrics[i]["Description"]} -- {round(float(get_node_importance(node_importance_matrix, node_id)[i]), 2)}'
    return result